INSERT INTO warehouse.fact_sales (...)
SELECT ...
FROM staging.stg_sales_transactions st
JOIN warehouse.dim_date dd ON ...
JOIN warehouse.dim_customer dc ON ...
JOIN warehouse.dim_product dp ON ...
JOIN warehouse.dim_store ds ON ...
LEFT JOIN warehouse.fact_sales fs ON fs.transaction_id = st.transaction_id
WHERE fs.transaction_id IS NULL;
